Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-0453ec754f44f9a4a"
      InstanceType: "t2.micro"
      KeyName: "formaskypem"
      SecurityGroupIds:
        - "sg-030159b8e28ebefd2"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello Guys This is  MyEC2Instance</h1>" > /var/www/html/index.html
      Tags:
        - Key: "Name"
          Value: "MyEC2Instance"
